# gsm.datasim —  Demo
# This script walks through the key functionality of the new datasim approach
library(gsm.datasim)

# ── DATA GENERATION ONLY ------------------------------------------------
# If you only need simulated raw data — no analytics, no reporting — use
# `create_longitudinal_study()` with both pipelines disabled.
# This is the fastest way to get Raw_* data frames across multiple snapshots.

data_only <- create_longitudinal_study(
  study_id         = "DATA-001",
  participants     = 200,
  sites            = 15,
  snapshots        = 6,
  interval         = "1 month",
  domains          = c("AE", "LB", "VISIT", "QUERY", "SUBJ"),
  run_analytics    = FALSE,  # skip analytics
  run_reporting    = FALSE,  # skip reporting
  verbose          = TRUE
)

# The study object has raw data but no analytics or reporting slots
names(data_only)          # $study_id, $config, $raw_data
names(data_only$raw_data) # one entry per snapshot date

# Peek at snapshots 1 and 4
snap <- data_only$raw_data[[1]]
snap4 <- data_only$raw_data[[4]]
names(snap)              # Raw_SUBJ, Raw_AE, Raw_LB, …
nrow(snap$Raw_SUBJ)      # participant count in first snap
nrow(snap4$Raw_SUBJ)     # participant count in 4th snap
nrow(snap$Raw_AE)        # AE records in first snapshot
nrow(snap4$Raw_AE)       # AE records in 4th snapshot


# ── QUICK START ------------------------------------------------
# `quick_longitudinal_study()` is the batteries-included entry point.
# It generates multi-snapshot raw data with the domain list generated by `study_type`.
# It runs the gsm.kri analytics pipeline and the gsm.reporting pipeline — all in one call.

study <- quick_longitudinal_study(
  study_name      = "DEMO-001",
  participants    = 200,
  sites           = 15,
  months_duration = 6,             # 6 monthly snapshots
  study_type      = "standard",
  include_pipeline = TRUE         # runs analytics + reporting (default)
)


# ── OUTLIER INTENSITY DEMO ------------------------------------------------
# Use `outlier_intensity` to increase/decrease outlier-like values that
# drive downstream flags in the analysis layer.

# Baseline behavior (current defaults)
baseline_study <- quick_longitudinal_study(
  study_name = "DEMO-OUTLIER-BASELINE",
  participants = 200,
  sites = 15,
  months_duration = 6,
  study_type = "standard",
  include_pipeline = TRUE,
  outlier_intensity = 1
)

# More aggressive outlier generation
high_outlier_study <- quick_longitudinal_study(
  study_name = "DEMO-OUTLIER-HIGH",
  participants = 200,
  sites = 15,
  months_duration = 6,
  study_type = "standard",
  include_pipeline = TRUE,
  outlier_intensity = 2.5
)

# The same option is available on create_longitudinal_study()
custom_outlier_study <- create_longitudinal_study(
  study_id = "DEMO-OUTLIER-CUSTOM",
  participants = 150,
  sites = 10,
  snapshots = 4,
  interval = "1 month",
  domains = c("AE", "LB", "VISIT", "QUERY"),
  run_analytics = TRUE,
  run_reporting = FALSE,
  outlier_intensity = 2
)


# ── THE STUDY OBJECT ------------------------------------------------
# The returned list has five top-level slots:

names(study)
# $study_id   — character study identifier
# $config     — study parameters (participants, sites, domains, intervals, …)
# $raw_data   — named list of snapshot data frames, one entry per snapshot date
# $analytics  — gsm.kri pipeline output, named by snapshot date
# $reporting  — gsm.reporting pipeline output, named by snapshot date


# ── RAW DATA ------------------------------------------------
# Snapshots are keyed by date (YYYY-MM-DD)
names(study$raw_data)

# Each snapshot is a named list of data frames (Raw_SUBJ, Raw_AE, Raw_LB, …)
snap_1 <- get_snapshot_data(study, 1)
names(snap_1)

cat("Subjects in snapshot 1:", nrow(snap_1$Raw_SUBJ), "\n")
cat("AE rows in snapshot 1: ", nrow(snap_1$Raw_AE),   "\n")

# Track a single domain across all snapshots
ae_timeline <- get_domain_timeline(study, "AE")
ae_counts   <- sapply(ae_timeline, nrow)
print(ae_counts)   # shows AE row growth over time

# All domains present anywhere in the study
get_available_domains(study)


# ── ANALYTICS PIPELINE RESULTS ------------------------------------------------
# study$analytics is a named list (one entry per snapshot).
# Each snapshot slot contains the raw gsm.core output:
#   $results   — named list of metric results (Analysis_kri0001, …)
#   $mapped    — mapped data frames (Mapped_SUBJ, Mapped_AE, Mapped_COUNTRY, …)
#   $lWorkflow — the workflow list used (useful for passing to reporting)
#   $summary   — lightweight metadata for the snapshot

snap_analytics <- study$analytics[["2012-01-31"]]  # adjust date to match your run
names(snap_analytics)

# All metric names computed for this snapshot
metric_names <- names(snap_analytics$results)
cat("Metrics computed:", paste(metric_names, collapse = ", "), "\n")

# Each metric result contains multiple data frames — no more by_site / by_country split
kri <- snap_analytics$results[[metric_names[1]]]
names(kri)  # e.g. Analysis_Summary, Analysis_Flagged, Analysis_Analyzed

kri$Analysis_Summary   # one row per site/country, with Score and Flag columns
kri$Analysis_Flagged   # subset of flagged entities
kri$Analysis_Analyzed  # full analyzed data before scoring

# Tally metrics across all snapshots
total <- sum(sapply(study$analytics, function(s) length(s$results)))
cat("Total metric results across all snapshots:", total, "\n")


# ── REPORTING PIPELINE RESULTS ------------------------------------------------
# study$reporting mirrors the analytics structure — one entry per snapshot,
# containing the raw gsm.reporting RunWorkflows output.

names(study$reporting)

snap_reporting <- study$reporting[["2012-01-31"]]
names(snap_reporting)  # Reporting_Results, Reporting_Bounds_Scatter, etc.


# ── STEPWISE PIPELINE EXECUTION  ------------------------------------------------
# You can build the study in stages rather than everything at once.
# This is useful when you want to inspect data before running heavy pipelines.

# Step 1 — raw data only
raw_study <- create_longitudinal_study(
  study_id         = "STEP-001",
  participants     = 100,
  sites            = 10,
  snapshots        = 4,
  interval         = "1 month",
  domains          = c("AE", "LB", "VISIT", "QUERY"),
  run_analytics    = FALSE,   # skip both pipelines
  run_reporting    = FALSE,
  verbose          = TRUE
)
names(raw_study)  # only $study_id, $config, $raw_data

# Step 2 — add analytics when ready
raw_study <- run_longitudinal_analytics(raw_study, verbose = TRUE)

# Step 3 — add reporting on top
raw_study <- run_longitudinal_reporting(raw_study, verbose = TRUE)

names(raw_study)  # now includes $analytics and $reporting


# ── 8. LOW-LEVEL CONFIG API ------------------------------------------------
# For full control over dataset counts, temporal settings, and which
# analytics / reporting packages / workflows to run, use the config API.
# All functions return a modified config so they compose with pipes.

custom_study <- create_study_config(
  study_id            = "CUSTOM-001",
  participant_count   = 300,
  site_count          = 20,
  analytics_package   = "gsm.kri",
  analytics_workflows = c("kri0001", "kri0002", "kri0003"),  # only these KRIs
  reporting_package   = "gsm.reporting"                       # default but explicit
) |>
  set_temporal_config(
    start_date     = "2023-06-01",
    snapshot_count = 12,
    snapshot_width = "months"
  ) |>
  add_dataset_config("Raw_AE",    enabled = TRUE) |>
  add_dataset_config("Raw_LB",    enabled = TRUE) |>
  add_dataset_config("Raw_VISIT", enabled = TRUE) |>
  add_dataset_config("Raw_QUERY", enabled = TRUE) |>
  add_dataset_config("Raw_DATACHG", enabled = TRUE,
    count_formula = function(config, snapshot_idx = 1) {
      round(config$study_params$participant_count * 0.4 * snapshot_idx /
              config$temporal_config$snapshot_count)
    }
  )

# Inspect before generating
str(custom_study$study_params)
str(custom_study$temporal_config)
names(custom_study$dataset_configs)

# Generate raw data from config
raw_data <- generate_raw_data_from_config(custom_study, verbose = TRUE)

# Run analytics
analytics <- generate_analytics_layers(raw_data, custom_study, verbose = TRUE)

# Run reporting
reporting <- generate_reporting_layers(analytics, custom_study, verbose = TRUE)

# Wrap into a study object if you want the helper functions
study_obj <- create_longitudinal_study_data(
  study_id = custom_study$study_params$study_id,
  raw_data = raw_data,
  config   = list(
    participants = custom_study$study_params$participant_count,
    sites        = custom_study$study_params$site_count,
    snapshots    = custom_study$temporal_config$snapshot_count,
    interval     = paste(1, custom_study$temporal_config$snapshot_width),
    domains      = gsub("^Raw_", "", names(custom_study$dataset_configs))
  )
)
study_obj$analytics  <- analytics
study_obj$reporting  <- reporting

summarize_longitudinal_study(study_obj)


# ── EXPORTING STUDY DATA ------------------------------------------------
# `export_study_data()` writes a completed study to a structured folder
# hierarchy on disk.  Every snapshot date becomes a subdirectory with up to
# four sub-folders:
#
#   <output_dir>/<study_id>/
#     <snapshot_date>/
#       raw/          ← Raw_*.csv
#       mapped/       ← Mapped_*.csv     (when analytics ran)
#       analytics/    ← <metric>_<table>.csv  (when analytics ran)
#       reporting/    ← Reporting_*.csv  (when reporting ran)
#
# Folders are only created when the data actually exists.

# Export the study created above to a temporary directory.
# Returns the path to the study root folder invisibly.
study_path <- export_study_data(
  study      = study,        # longitudinal_study object from quick_longitudinal_study()
  output_dir = tempdir(),    # top-level root (default: getwd())
  verbose    = TRUE          # print per-snapshot progress
)

# ── Export options ------------------------------------------------

# Specify a different root folder and/or override the study folder name
export_study_data(
  study        = study,
  output_dir   = ".",
  format = "parquet",
  study_folder = "DEMO-001-export",  # instead of deriving from study_id
  overwrite    = TRUE                # allow re-running without error
)

# save_rds = TRUE writes analytics_full.rds per snapshot alongside the CSVs,
# preserving workflow lists, summaries, and other non-data-frame objects.
rds_path <- export_study_data(
  study      = study,
  output_dir = tempdir(),
  overwrite  = TRUE,
  save_rds   = TRUE
)

# Reload the full analytics object from the first snapshot
analytics_snap <- readRDS(file.path(rds_path, snap_date, "analytics_full.rds"))
names(analytics_snap)  # $results, $mapped, $lWorkflow, $summary


# ── CREATING MULTIPLE STUDIES ------------------------------------------------
# `create_multiple_longitudinal_studies()` generates several studies in one call.
# Pass shared settings as scalars (applied to all) or vectors (one per study).

# Basic usage: three studies with identical configuration
portfolio <- create_multiple_longitudinal_studies(
  study_names  = c("TRIAL-001", "TRIAL-002", "TRIAL-003"),
  participants = 150,
  sites        = 12,
  snapshots    = 4,
  domains      = c("AE", "LB", "VISIT"),
  run_analytics = FALSE,
  verbose      = TRUE
)

# The result is a named list of longitudinal_study objects
names(portfolio)                  # "TRIAL-001", "TRIAL-002", "TRIAL-003"
length(portfolio[["TRIAL-001"]]$raw_data)  # 4 snapshots

# Per-study configuration: different sizes, domains, or intervals
portfolio_mixed <- create_multiple_longitudinal_studies(
  study_names  = c("PHASE2-SMALL", "PHASE3-LARGE"),
  participants = c(50, 300),       # 50 for PHASE2, 300 for PHASE3
  sites        = c(5, 20),         # 5 sites vs 20 sites
  snapshots    = c(3, 12),         # 3 vs 12 snapshots
  study_configs = list(
    "PHASE2-SMALL" = list(domains = c("AE", "LB")),
    "PHASE3-LARGE" = list(domains = c("AE", "LB", "VISIT", "PD", "PK"))
  ),
  run_analytics = FALSE,
  verbose      = TRUE
)

# Print and summary methods give a quick overview
print(portfolio_mixed)
summary(portfolio_mixed)

cat("Study exported to:", study_path, "\n")

# Inspect the folder structure
dirs <- list.dirs(study_path, full.names = FALSE, recursive = TRUE)
cat("Folders created:\n")
closest_dirs <- dirs[dirs != ""]
cat(paste(" ", sort(closest_dirs), collapse = "\n"), "\n")

# Count CSVs written
all_csvs <- list.files(study_path, pattern = "\\.csv$", recursive = TRUE)
cat(length(all_csvs), "CSV files written\n")

# Read a raw dataset back in from the first snapshot
snap_date <- names(study$raw_data)[1]
ae_back   <- read.csv(file.path(study_path, snap_date, "raw", "Raw_AE.csv"))
nrow(ae_back)  # should match nrow(study$raw_data[[1]]$Raw_AE)


# ── EXPORTING MULTIPLE STUDIES ------------------------------------------------
# `export_study_data()` also accepts a `multiple_longitudinal_studies` object.
# Each study is written to its own subfolder under `output_dir`.

export_study_data(
  study      = portfolio,        # from the "CREATING MULTIPLE STUDIES" section above
  output_dir = ".",
  format     = "parquet",        # export all studies as parquet
  overwrite  = TRUE,
  verbose    = TRUE
)
